# TEST PATTERN ( ONLY SUCCESS )
# - INDEX
#   - BEFORE: LOGIN AND GO TO SOME POST SHOW PAGE
#   - ALREADY SAVED POST'S COMMENT DISPLAY IN THE LIST ( post.comments.last or first )
#   - CHECK ID ASC IN THE LIST ( Comment.first.id )
# - NEW & CREATE
#   - BEFORE: LOGIN AND GO TO SOME POST SHOW PAGE
#   - INPUT FORM AND SUBMIT
# - EDIT & UPDATE
#   - BEFORE: LOGIN AND GO TO SOME POST SHOW PAGE
#   - CHECK EDIT BUTTON SHOW AND INPUT FORM AND SUBMIT
# - DESTROY
#   - BEFORE: LOGIN AND GO TO SOME POST SHOW PAGE
#   - CHECK DESTROY BUTTON SHOW AND CLICK CAN DESTROY

#no one writes comment_spec do i really have to write ?? 